.\"                                      Hey, EMACS: -*- nroff -*-
.\" Please adjust this date whenever revising the manpage.
.Dd Sep 13, 2013
.Dt MUSAD 1
.Sh NAME
.Nm musad.py
.Nd The server side for the open source uploader tool for OpenTTD's content service
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
This is the server side for the musa uploader of content into OpenTTD's
content server. Since one cannot easily configure different content servers
in OpenTTD, it makes no sense to run this on a private server. Furthermore
neither the actual server application for making the content accessible in
OpenTTD, nor the website to view and manage the content are included in this
package.
.Sh SEE ALSO
http://bananas.openttd.org/
